apiVersion: v1
kind: Service
metadata:
  name: bullmq-metrics
  namespace: sparrowdesk
spec:
  selector:
    app: bullmq-metrics
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: ClusterIP
